### PR TITLE
Migrate `modules\sdp\SDPUtil.js`

### PR DESCRIPTION
**Pull request by naman9271**

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Jenkins please test this please.

**Comment by naman9271** [comment]
failing test fixed please take a look.

**Comment by naman9271** [comment]
Rebased and conflicts resolved

**Comment by naman9271** [comment]
Rebased and conflicts resolved please take a look

**Comment by jallamsetty1** [comment]
Jenkins test this please.

**Comment by naman9271** [comment]
Ping @jallamsetty1

**Comment by jallamsetty1** [comment]
Jenkins test this please.

**Comment by naman9271** [comment]
Jenkins Passed successfully🕺🕺

**Comment by damencho** [comment]
@jallamsetty1 @naman9271 
After merging this, there are a bunch of build errors:

```
modules/RTC/TPCUtils.ts(805,44): error TS2345: Argument of type '{ type: string; port: number; protocol: string; payloads?: string; } & MediaDescription' is not assignable to parameter of type 'IMLine'.
  Property 'payloads' is optional in type '{ type: string; port: number; protocol: string; payloads?: string; } & MediaDescription' but required in type 'IMLine'.
modules/RTC/TPCUtils.ts(810,44): error TS2345: Argument of type '{ type: string; port: number; protocol: string; payloads?: string; } & MediaDescription' is not assignable to parameter of type 'IMLine'.
  Property 'payloads' is optional in type '{ type: string; port: number; protocol: string; payloads?: string; } & MediaDescription' but required in type 'IMLine'.
modules/RTC/TPCUtils.ts(818,41): error TS2345: Argument of type '{ type: string; port: number; protocol: string; payloads?: string; } & MediaDescription' is not assignable to parameter of type 'IMLine'.
  Property 'payloads' is optional in type '{ type: string; port: number; protocol: string; payloads?: string; } & MediaDescription' but required in type 'IMLine'.
npm error code 2
```

**Comment by jallamsetty1** [comment]
> @jallamsetty1 @naman9271 After merging this, there are a bunch of build errors:
> 
> ```
> modules/RTC/TPCUtils.ts(805,44): error TS2345: Argument of type '{ type: string; port: number; protocol: string; payloads?: string; } & MediaDescription' is not assignable to parameter of type 'IMLine'.
>   Property 'payloads' is optional in type '{ type: string; port: number; protocol: string; payloads?: string; } & MediaDescription' but required in type 'IMLine'.
> modules/RTC/TPCUtils.ts(810,44): error TS2345: Argument of type '{ type: string; port: number; protocol: string; payloads?: string; } & MediaDescription' is not assignable to parameter of type 'IMLine'.
>   Property 'payloads' is optional in type '{ type: string; port: number; protocol: string; payloads?: string; } & MediaDescription' but required in type 'IMLine'.
> modules/RTC/TPCUtils.ts(818,41): error TS2345: Argument of type '{ type: string; port: number; protocol: string; payloads?: string; } & MediaDescription' is not assignable to parameter of type 'IMLine'.
>   Property 'payloads' is optional in type '{ type: string; port: number; protocol: string; payloads?: string; } & MediaDescription' but required in type 'IMLine'.
> npm error code 2
> ```

Thanks Damyan, fixed in https://github.com/jitsi/lib-jitsi-meet/pull/2917
