### ISSUE TITLE
crashes on iOS 14 / 15 with d.getHeight is not a function.  'd.getHeight' is undefined

### ISSUE THREAD

**Issue by Corey-Maler** [jitsi/lib-jitsi-meet#2379]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Crashes on iOS 14 / 15 with error "l.getHeight is not a function (getHeight is undefined)"

After digging a bit, I found that it refers to this line https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/JitsiLocalTrack.js#L115

This change was introduced in https://github.com/jitsi/lib-jitsi-meet/pull/2356 this PR.

I assume it is a confusion here since `track` at that line refers to the native MediaStreamTrack which does not have `getHeight` method and since it is under condition, it does not work only for specific safari versions

## Current behavior
Cannot enable camera, "failed to access your camera" is displayed

(Technically)
`createLocalTrack` crashes with an error

## Expected Behavior
Camera works

(Technically)
`createLocalTrack` does not crash with an error

## Steps to reproduce
Open https://beta.meet.jit.si on any iOS 14 or 15, not even necessary to start a call

**Comment by saghul** [comment]
@gabiborlea can you PTAL?

**Comment by gabiborlea** [comment]
You are right, I'll create a PR to fix this!

**Comment by gabiborlea** [comment]
Fixed with this PR: https://github.com/jitsi/lib-jitsi-meet/pull/2380.
